### PR TITLE
Add Tewr.BlazorWorker.Core Examples

### PR DESCRIPTION
**Pull request by Tewr**
Hello,

I read your article and I think it was interesting. My library has a "Core" mode that can be used that does not use any serializer. So it's a lot more contrived to use, but i'ts comparable in speed to the other examples in your article, that's why I thought it could be interesting to add it to your comparison. 

Regards

### CODE REVIEW

**Comment by KristofferStrube** [comment]
Hey @Tewr awesome!

I've checked out the demos and they look solid. I might do a follow-up article or an update to my original article with these extra comparisons.

Before we merge I see this error when trying out the Tewr.BlazorWorker.Core benchmark in the Sum Even Numbers page:
```js
blazor.webassembly.js:1 Uncaught Error: JS object instance with Id '19' does not exist. It may have been disposed.
    at blazor.webassembly.js:1:5849
    at blazor.webassembly.js:1:1538
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (blazor.webassembly.js:1:1523)
    at JSON.parse (<anonymous>)
    at v (blazor.webassembly.js:1:1505)
    at b.invokeDotNetMethod (blazor.webassembly.js:1:3522)
    at S.invokeMethod (blazor.webassembly.js:1:5372)
    at worker.onmessage (2580489f-f1d0-41b7-a…89dc7b08c2fc:267:30)
```

Do you know what could cause that?

**Comment by Tewr** [comment]
I'm not sure where it comes from. I'm unable to reproduce in my demo project. may be a conflict with one of the other libraries perhaps. However, unless I'm mistaken this error message is already present in the main branch of your benchmark when launching the blazorworker example.

**Comment by Tewr** [comment]
I you remove all references to SpawnDev in your project, the errors no longer occur. So it's clearly a conflict between My library and Spawndev.

**Comment by KristofferStrube** [comment]
That makes a lot of sense. :) I will merge your branch here and then open an issue with SpawnDev on his library breaking other libraries.

**Pull request merged**
